from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CompanyTarget:
    name: str
    market: str
    status: str
    careers_url: str = ""


TARGET_COMPANIES = (
    CompanyTarget("DRW", "London / Amsterdam", "greenhouse", "https://www.drw.com/work-at-drw/listings"),
    CompanyTarget("Jane Street", "London", "greenhouse", "https://www.janestreet.com/join-jane-street/open-roles/"),
    CompanyTarget("Citadel / Citadel Securities", "London", "custom", "https://www.citadelsecurities.com/careers/"),
    CompanyTarget("G-Research", "London", "custom", "https://www.gresearch.com/careers/"),
    CompanyTarget("XTX Markets", "London", "custom", "https://www.xtxmarkets.com/careers/"),
    CompanyTarget("Jump Trading", "London", "greenhouse", "https://www.jumptrading.com/careers/"),
    CompanyTarget("Two Sigma", "London", "custom", "https://www.twosigma.com/careers/"),
    CompanyTarget("Optiver", "London / Amsterdam", "greenhouse", "https://optiver.com/working-at-optiver/career-opportunities/"),
    CompanyTarget("IMC Trading", "London / Amsterdam", "greenhouse", "https://www.imc.com/eu/careers"),
    CompanyTarget("Flow Traders", "Amsterdam", "greenhouse", "https://www.flowtraders.com/careers/"),
    CompanyTarget("Millennium Management", "London", "custom", "https://www.mlp.com/careers/"),
    CompanyTarget("Man AHL", "London", "custom", "https://www.man.com/careers"),
    CompanyTarget("Point72", "London", "greenhouse", "https://careers.point72.com/"),
    CompanyTarget("Qube Research & Technologies", "London / Amsterdam", "custom", "https://www.qube-rt.com/careers"),
    CompanyTarget("Schonfeld", "London", "greenhouse", "https://www.schonfeld.com/careers"),
    CompanyTarget("Maven Securities", "London / Amsterdam", "custom", "https://www.maven.co.uk/careers"),
    CompanyTarget("Cubist", "London", "custom", "https://www.citadel.com/careers/"),
    CompanyTarget("D. E. Shaw", "London", "custom", "https://www.deshaw.com/careers"),
    CompanyTarget("Hudson River Trading", "London", "custom", "https://www.hudsonrivertrading.com/careers/"),
    CompanyTarget("SIG", "London", "custom", "https://sig.com/careers/"),
    CompanyTarget("Tower Research Capital", "London", "custom", "https://www.tower-research.com/open-positions/"),
    CompanyTarget("Virtu Financial", "London", "custom", "https://www.virtu.com/careers/"),
    CompanyTarget("Akuna Capital", "London", "custom", "https://akunacapital.com/careers"),
    CompanyTarget("Belvedere Trading", "London", "custom", "https://belvederetrading.com/careers/"),
    CompanyTarget("Quantlab", "London", "custom", "https://www.quantlab.com/careers/"),
    CompanyTarget("Radix Trading", "London", "custom", "https://radixtrading.co/careers/"),
    CompanyTarget("Brevan Howard", "London", "custom", "https://www.brevanhoward.com/careers/"),
    CompanyTarget("Marshall Wace", "London", "custom", "https://www.mwam.com/careers/"),
    CompanyTarget("Capula Investment Management", "London", "custom", "https://www.capulaglobal.com/careers/"),
    CompanyTarget("Winton Group", "London", "custom", "https://www.winton.com/careers"),
    CompanyTarget("Aspect Capital", "London", "custom", "https://www.aspectcapital.com/careers/"),
    CompanyTarget("Systematica Investments", "London", "custom", "https://systematica.com/careers/"),
    CompanyTarget("GSA Capital", "London", "custom", "https://www.gsacapital.com/careers/"),
    CompanyTarget("Man Group", "London", "custom", "https://www.man.com/careers"),
    CompanyTarget("PDT Partners", "London", "custom", "https://www.pdtpartners.com/careers/"),
    CompanyTarget("Cboe", "Amsterdam", "custom", "https://careers.cboe.com/"),
    CompanyTarget("Da Vinci Derivatives", "Amsterdam", "custom", "https://davinciderivatives.com/careers/"),
    CompanyTarget("All Options", "Amsterdam", "custom", "https://www.alloptions.nl/careers/"),
    CompanyTarget("Bloomberg", "London", "custom", "https://www.bloomberg.com/company/careers/"),
    CompanyTarget("Wise", "London", "greenhouse", "https://wise.jobs/"),
    CompanyTarget("Revolut", "London", "custom", "https://www.revolut.com/careers/"),
    CompanyTarget("Monzo", "London", "greenhouse", "https://monzo.com/careers"),
    CompanyTarget("Starling Bank", "London", "custom", "https://www.starlingbank.com/careers/"),
    CompanyTarget("Checkout.com", "London", "custom", "https://www.checkout.com/careers"),
    CompanyTarget("Adyen", "Amsterdam", "greenhouse", "https://careers.adyen.com/"),
    CompanyTarget("Stripe", "London / Amsterdam", "greenhouse", "https://stripe.com/jobs"),
    CompanyTarget("Deliveroo", "London", "custom", "https://careers.deliveroo.co.uk/"),
    CompanyTarget("Ocado Technology", "London", "custom", "https://www.ocadogroup.com/careers/"),
    CompanyTarget("Cloudflare", "London / Amsterdam", "greenhouse", "https://www.cloudflare.com/careers/"),
    CompanyTarget("Databricks", "London / Amsterdam", "greenhouse", "https://www.databricks.com/company/careers"),
    CompanyTarget("Snowflake", "London", "custom", "https://careers.snowflake.com/"),
    CompanyTarget("Elastic", "London / Amsterdam", "greenhouse", "https://www.elastic.co/about/careers"),
    CompanyTarget("Palantir", "London", "lever", "https://www.palantir.com/careers/"),
    CompanyTarget("Canonical", "London", "greenhouse", "https://canonical.com/careers"),
    CompanyTarget("Spotify", "London", "lever", "https://www.lifeatspotify.com/jobs"),
    CompanyTarget("Booking.com", "Amsterdam", "custom", "https://careers.booking.com/"),
    CompanyTarget("Uber", "Amsterdam", "custom", "https://www.uber.com/careers/"),
    CompanyTarget("Mollie", "Amsterdam", "custom", "https://www.mollie.com/careers"),
    CompanyTarget("Backbase", "Amsterdam", "custom", "https://www.backbase.com/company/careers"),
    CompanyTarget("Picnic", "Amsterdam", "custom", "https://jobs.picnic.app/"),
    CompanyTarget("TomTom", "Amsterdam", "custom", "https://www.tomtom.com/careers/"),
    CompanyTarget("Bunq", "Amsterdam", "custom", "https://www.bunq.com/careers"),
    CompanyTarget("WeTransfer", "Amsterdam", "custom", "https://wetransfer.com/careers"),
    CompanyTarget("Catawiki", "Amsterdam", "greenhouse", "https://www.catawiki.com/en/jobs"),
    CompanyTarget("Tide", "London", "greenhouse", "https://www.tide.co/careers/"),
    CompanyTarget("SumUp", "London", "greenhouse", "https://www.sumup.com/careers/"),
    CompanyTarget("Celonis", "London", "greenhouse", "https://careers.celonis.com/"),
    CompanyTarget("MongoDB", "London", "greenhouse", "https://www.mongodb.com/careers"),
    CompanyTarget("Fastly", "London", "greenhouse", "https://www.fastly.com/about/careers"),
    CompanyTarget("Twilio", "London", "greenhouse", "https://www.twilio.com/company/jobs"),
    CompanyTarget("Okta", "London", "greenhouse", "https://www.okta.com/company/careers/"),
    CompanyTarget("Fivetran", "London", "greenhouse", "https://www.fivetran.com/careers"),
    CompanyTarget("GoCardless", "London", "greenhouse", "https://gocardless.com/careers/"),
    CompanyTarget("TrueLayer", "London", "greenhouse", "https://www.truelayer.com/careers/"),
    CompanyTarget("Graphcore", "London", "greenhouse", "https://www.graphcore.ai/careers"),
    CompanyTarget("Wayve", "London", "greenhouse", "https://wayve.ai/careers/"),
    CompanyTarget("Scale AI", "London", "greenhouse", "https://scale.com/careers"),
    CompanyTarget("Veriff", "London", "greenhouse", "https://www.veriff.com/careers"),
    CompanyTarget("Trustpilot", "London", "greenhouse", "https://www.trustpilot.com/careers"),
    CompanyTarget("HelloFresh", "London", "greenhouse", "https://www.hellofreshgroup.com/en/careers/"),
    CompanyTarget("commercetools", "London", "greenhouse", "https://commercetools.com/careers"),
    CompanyTarget("Contentsquare", "London", "lever", "https://www.contentsquare.com/en_gb/careers/"),
    CompanyTarget("Zopa", "London", "lever", "https://www.zopa.com/careers"),
    CompanyTarget("Brex", "London", "greenhouse", "https://www.brex.com/careers"),
    CompanyTarget("Affirm", "London", "greenhouse", "https://www.affirm.com/careers"),
    CompanyTarget("N26", "Amsterdam", "greenhouse", "https://n26.com/en-eu/careers"),
    CompanyTarget("Datadog", "London / Amsterdam", "greenhouse", "https://careers.datadoghq.com/"),
    CompanyTarget("Reddit", "London", "greenhouse", "https://www.redditinc.com/careers"),
    CompanyTarget("GitLab", "London / Amsterdam", "greenhouse", "https://about.gitlab.com/jobs/"),
    CompanyTarget("Lyft", "London", "greenhouse", "https://www.lyft.com/careers"),
    CompanyTarget("Coinbase", "London", "greenhouse", "https://www.coinbase.com/careers"),
)

VERIFIED_GREENHOUSE_BOARDS = {
    "drweng": "DRW",
    "janestreet": "Jane Street",
    "jumptrading": "Jump Trading",
    "imc": "IMC Trading",
    "flowtraders": "Flow Traders",
    "wise": "Wise",
    "adyen": "Adyen",
    "databricks": "Databricks",
    "elastic": "Elastic",
    "canonical": "Canonical",
    "catawiki": "Catawiki",
    "schonfeld": "Schonfeld",
    "point72": "Point72",
    "stripe": "Stripe",
    "cloudflare": "Cloudflare",
    "monzo": "Monzo",
    "brex": "Brex",
    "affirm": "Affirm",
    "n26": "N26",
    "datadog": "Datadog",
    "reddit": "Reddit",
    "gitlab": "GitLab",
    "lyft": "Lyft",
    "coinbase": "Coinbase",
    "tide": "Tide",
    "sumup": "SumUp",
    "celonis": "Celonis",
    "mongodb": "MongoDB",
    "fastly": "Fastly",
    "twilio": "Twilio",
    "okta": "Okta",
    "fivetran": "Fivetran",
    "gocardless": "GoCardless",
    "truelayer": "TrueLayer",
    "graphcore": "Graphcore",
    "wayve": "Wayve",
    "scaleai": "Scale AI",
    "veriff": "Veriff",
    "trustpilot": "Trustpilot",
    "hellofresh": "HelloFresh",
    "commercetools": "commercetools",
}

VERIFIED_LEVER_BOARDS = {
    "palantir": "Palantir",
    "spotify": "Spotify",
    "contentsquare": "Contentsquare",
    "zopa": "Zopa",
}